=== gitnew22/xml/banco.dtd
<!ELEMENT banco (sucursal+)>
<!ELEMENT sucursal (cuenta_corriente+,prestamos+)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT cuenta_corriente (clientes*,domiciliaciones)>
<!ATTLIST cuenta_corriente codigo CDATA #REQUIRED>
<!ELEMENT clientes (operacion,privilegio)>
<!ATTLIST clientes nif CDATA #REQUIRED>
<!ELEMENT operacion (#PCDATA)>
<!ELEMENT privilegio (#PCDATA)>
<!ELEMENT domiciliaciones (#PCDATA)>
<!ELEMENT prestamos (#PCDATA)>

=== gitnew22/xml/banco.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "banco.dtd">
<banco>
  <sucursal codigo="1">
    <cuenta_corriente codigo="2">
      <clientes nif="345095345">
        <operacion></operacion>
        <privilegio></privilegio>
      </clientes>
      <domiciliaciones></domiciliaciones>
    </cuenta_corriente>
    <prestamos></prestamos>
  </sucursal>
</banco>
