=== gitnew22/xml/financieros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="productosfinancieros">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="producto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice>
              <xs:element name="bono" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                  <xs:element name="valoractual" maxOccurs="unbounded">
                    <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                        <xs:fractionDigits value="2"/>
                      </xs:restriction>
                    </xs:simpleType>
                        <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="moneda" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                  </xs:element>
                  <xs:element name="beneficio">
                    <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                        <xs:fractionDigits value="2"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="futuro" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="elemento" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="idioma" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="beneficio" type="decimal" maxOccurs="unbounded">
                      <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:fractionDigits value="2"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="acciones" maxOccurs="unbounded"></xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gitnew22/xml/financieros.xml
<?xml version="1.0" encoding="UTF-8"?>
<productosfinancieros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="financieros.xsd">
  <producto>
    <bono>
      <valoractual moneda="yenes">2.212</valoractual>
      <beneficio>-2.83</beneficio>
    </bono>
  </producto>
  <producto>
    <futuro>
      <elemento idioma="español">petroleo</elemento>
      <beneficio>-3.83</beneficio>
    </futuro>
  </producto>
  <producto>
    <acciones>
      <empresa pais="usa">enron</empresa>
      <beneficio>2.91</beneficio>
    </acciones>
  </producto>
</productosfinancieros>
