=== gitnew22/xml/hechoshistoricos.dtd
<!ELEMENT hechos_historicos (hecho_historico+)>
<!ELEMENT hecho_historico (fecha+)>
<!ATTLIST hecho_historico descripcion CDATA #REQUIRED>
<!ELEMENT fecha (dia,mes,anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== gitnew22/xml/hechoshistoricos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hechos_historicos SYSTEM "hechoshistoricos.dtd">
<hechos_historicos>
  <hecho_historico descripcion="Ibm da a conocer el pc">
    <fecha>
      <dia>12</dia>
      <mes>8</mes>
      <anio>81</anio>
    </fecha>
  </hecho_historico>
  <hecho_historico descripcion="Se funda Google">
    <fecha>
      <dia>4</dia>
      <mes>9</mes>
      <anio>98</anio>
    </fecha>
  </hecho_historico>
  <hecho_historico descripcion="Se funda Facebook">
    <fecha>
      <dia>4</dia>
      <mes>2</mes>
      <anio>2004</anio>
    </fecha>
  </hecho_historico>
</hechos_historicos>
