=== gitnew22/xml/heladeria.xsd
﻿<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="heladeria">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="helado" maxOccurs="unbounded">
            <xs:complexType>
              <xs:choice>
                <xs:sequence>
                  <xs:element name="fresa"/>
                  <xs:element name="chocolate"/>
                </xs:sequence>
                <xs:sequence>
                  <xs:element name="vainilla"/>
                  <xs:element name="chocolate"/>
                </xs:sequence>
              </xs:choice>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
=======
﻿<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="heladeria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="helado" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    <xs:complexType name="helado">
    <xs:sequence>
      <xs:choice>
        <xs:element name="fresa"/>
        <xs:element name="vainilla"/>
      </xs:choice>
      <xs:element name="chocolate"/>
    </xs:sequence>
   </xs:complexType>
</xs:schema>
>>>>>>> fcac7ec615b617e9deaa29bbb73da82ee9fdc546

=== gitnew22/xml/heladeria.xml
﻿<?xml version="1.0" encoding="UTF-8"?>
<heladeria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="heladeria.xsd">
    <helado>
        <fresa/>
        <chocolate/>
    </helado>
    <helado>
        <vainilla/>
        <chocolate/>
    </helado>
</heladeria>

﻿<?xml version="1.0" encoding="UTF-8"?>
<heladeria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="heladeria.xsd">
    <helado>
        <fresa/>
        <chocolate/>
   </helado>
    <helado>
        <vainilla/>
        <chocolate/>
    </helado>
</heladeria>
>>>>>>> fcac7ec615b617e9deaa29bbb73da82ee9fdc546
