=== gitnew22/xml/instituto2.dtd
<!ELEMENT instituto (nombre,direccion,profesores,alumnos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (nompro,profepro,telpro+)>
<!ELEMENT nompro (#PCDATA)>
<!ELEMENT profepro (#PCDATA)>
<!ELEMENT telpro (#PCDATA)>
<!ATTLIST telpro tipo CDATA #IMPLIED>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombrealu,apellido1,apellido2,foto?,telefono+)>
<!ELEMENT nombrealu (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT foto EMPTY>
<!ATTLIST foto archivo CDATA #REQUIRED>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo CDATA #REQUIRED>

=== gitnew22/xml/instituto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE instituto SYSTEM "instituto2.dtd">
<instituto>
  <nombre>lio</nombre>
  <direccion>kyjh</direccion>
  <profesores>
    <profesor>
      <nompro>dfv</nompro>
      <profepro>ghh</profepro>
      <telpro tipo="fijo">688898456</telpro>
      <telpro tipo="movil">688898456</telpro>
   </profesor>
  </profesores>
  <alumnos>
    <alumno>
      <nombrealu>yuyu</nombrealu>
      <apellido1>hgfhy</apellido1>
      <apellido2>eerre</apellido2>
      <foto archivo="jpg"/>
      <telefono tipo="movil">3453534</telefono>
       <telefono tipo="fijo">34535876834</telefono>
    </alumno>
  </alumnos>
  </instituto>
