=== gitnew22/xml/instituto.dtd
<!ELEMENT p:instituto (p:pas,profe:profesores,alu:alumnos)>
<!ATTLIST p:instituto xmlns:p CDATA #FIXED "http://es.wiki/espacio/xml/pas">
<!ATTLIST p:instituto xmlns:profe CDATA #FIXED "http://es.wiki/espacio/xml/profesor">
<!ATTLIST p:instituto xmlns:alu CDATA #FIXED "http://es.wiki/espacio/xml/alumnos">
<!ATTLIST p:instituto especialidad CDATA #REQUIRED>
<!ELEMENT p:pas (p:nombre,p:apellidos,p:puesto,p:telefono)>
<!ELEMENT p:nombre (#PCDATA)>
<!ELEMENT p:apellidos (#PCDATA)>
<!ELEMENT p:puesto (#PCDATA)>
<!ELEMENT p:telefono (#PCDATA)>
<!ELEMENT profe:profesores (profe:nombre,profe:apellidos,profe:puesto,profe:telefono)>
<!ELEMENT profe:nombre (#PCDATA)>
<!ELEMENT profe:apellidos (#PCDATA)>
<!ELEMENT profe:puesto (#PCDATA)>
<!ELEMENT profe:telefono (#PCDATA)>
<!ELEMENT alu:alumnos (alu:nombre,alu:apellidos,alu:puesto,alu:telefono)>
<!ELEMENT alu:nombre (#PCDATA)>
<!ELEMENT alu:apellidos (#PCDATA)>
<!ELEMENT alu:puesto (#PCDATA)>
<!ELEMENT alu:telefono (#PCDATA)>

=== gitnew22/xml/instituto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE p:instituto SYSTEM "instituto.dtd">
<p:instituto especialidad="ciencias">
  <p:pas>
    <p:nombre>rober</p:nombre>
    <p:apellidos>gutierrez</p:apellidos>
    <p:puesto>oficial</p:puesto>
    <p:telefono>49586392323</p:telefono>
  </p:pas>
  <profe:profesores>
    <profe:nombre>jorge</profe:nombre>
    <profe:apellidos>marcano</profe:apellidos>
    <profe:puesto>jefe</profe:puesto>
    <profe:telefono>56903094234</profe:telefono>
  </profe:profesores>
  <alu:alumnos>
    <alu:nombre>pedro</alu:nombre>
    <alu:apellidos>gutierrez</alu:apellidos>
    <alu:puesto>gerente</alu:puesto>
    <alu:telefono>5490690307345</alu:telefono>
  </alu:alumnos>
</p:instituto>
