=== gitnew22/xml/matricula.dtd
<!ELEMENT matricula (personal+,pago+)>
<!ELEMENT personal (dni,nombrep,titulacion,curso_academico,domicilios+)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombrep (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio+)>
<!ELEMENT domicilio (nombre)>
<!ATTLIST domicilio tipo CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pago (tipo)>
<!ELEMENT tipo (#PCDATA)>
<!ATTLIST tipo matricula CDATA #IMPLIED>

=== gitnew22/xml/matricula.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "matricula.dtd">

<matricula>
 <personal>
    <dni>99223366M</dni>
    <nombrep>Juan Pardo Martín</nombrep>
    <titulacion>Ingeniería Informática</titulacion>
    <curso_academico>1997/1998</curso_academico>
    <domicilios>
      <domicilio tipo="Familiar">
        <nombre></nombre>
      </domicilio>
      <domicilio tipo="Habitual">
        <nombre></nombre>
      </domicilio>
    </domicilios>
  </personal>
  <pago>
    <tipo matricula="">matricula mensual</tipo>
  </pago> 
</matricula>
