=== gitnew22/xml/nacimientos.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,nacimiento?,direccion+)>
<!ATTLIST persona genero CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento (dia,mes,anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT direccion (calle,poblacion,provincia,cpostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>

=== gitnew22/xml/nacimientos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "nacimientos.dtd">

<personas>
  <persona genero="mujer">
    <nombre>alicia</nombre>
    <nacimiento>
      <dia>3</dia>
      <mes>6</mes>
      <anyo>98</anyo>
    </nacimiento> 
    <direccion>
      <calle>los peligros</calle>
      <poblacion>gulapa</poblacion>
      <provincia>caceres</provincia>
      <cpostal>45876</cpostal>
    </direccion>
  </persona>
</personas>
