=== gitnew22/xml/pago.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pagos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="anombre" maxOccurs="3" default="A"/>
        <xs:element name="fecha" type="afecha"/>
        <xs:element name="hora" type="xs:time" maxOccurs="unbounded"/>
        <xs:element name="precio" type="xs:decimal"/>
        <xs:element name="cantidad" type="xs:string" fixed="678"/>
        <xs:element name="pagado" type="xs:string" default="false"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   <xs:complexType name="anombre">
    <xs:simpleContent>
      <xs:extension base="xs:string">
         <xs:attribute name="dni" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:maxLength value="10"/>
              </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="afecha">
    <xs:simpleContent>
      <xs:extension base="xs:date">
        <xs:attribute name="edad">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="16"/>
              <xs:maxInclusive value="24"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== gitnew22/xml/pagoatributo.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation="pago.xsd">
  <nombre dni="1234567890">javier</nombre>
  <fecha>1430-03-03</fecha>
  <hora>23:44:22</hora>
  <hora>23:33:22</hora>
  <precio>123.45</precio>
  <cantidad>678</cantidad>
  <pagado>true</pagado>
</pagos>
