=== gitnew22/xml/peliculilla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pelicula" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="duracion" maxOccurs="unbounded"/>
              <xs:element name="actores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="actor" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="fecha" maxOccurs="unbounded"/>
              <xs:element name="director" maxOccurs="unbounded"/>
              <xs:element name="titulo" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="genero"/>
          </xs:complexType>
        </xs:element> 
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gitnew22/xml/peliculilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="peliculilla.xsd">
    <pelicula genero="terror">
        <duracion>30</duracion>
        <actores>
            <actor>dracula</actor>
            <actor>franki</actor>
        </actores>
        <fecha>12-21-98</fecha>
        <director>escorsese</director>
        <titulo>guillotina</titulo>
    </pelicula>
    <pelicula genero="aventura">
        <duracion>40</duracion>
        <actores>
            <actor>faraday</actor>
            <actor>kit dugla</actor>
        </actores>
        <fecha>12-01-99</fecha>
        <director>jhon</director>
        <titulo>fondo de la tierra</titulo>
    </pelicula>
    <pelicula genero="drama">
        <duracion>50</duracion>
        <actores>
            <actor>yeen</actor>
            <actor>yeek</actor>
        </actores>
        <fecha>12-11-58</fecha>
        <director>escorsese</director>
        <titulo>divorcio</titulo>
    </pelicula>
    <pelicula genero="suspense">
        <duracion>70</duracion>
        <actores>
            <actor>simon</actor>
            <actor>grum</actor>
        </actores>
        <fecha>12-21-98</fecha>
        <director>escorsese</director>
        <titulo>susto</titulo>
    </pelicula>
</catalogo>
