=== gitnew22/xml/sistemaSolar.dtd
<!ELEMENT sistemaSolar (cuerpo*)>
<!ELEMENT cuerpo ((planeta|satelite|asteroide)*)>
<!ELEMENT planeta (#PCDATA)>
<!ELEMENT satelite (#PCDATA)>
<!ELEMENT asteroide (#PCDATA)>

=== gitnew22/xml/sistemaSolar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar SYSTEM "sistemasolar.dtd">
<sistemaSolar>
  <cuerpo>
    <planeta>venus</planeta>
     <planeta>tierra</planeta>
      <planeta>marte</planeta>
       <planeta>jupiter</planeta>
       <satelite>luna</satelite>
       <asteroide>pum</asteroide>
  </cuerpo>
</sistemaSolar>
