=== gitnew22/xml/win.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="faq">
    <xs:complexType>
      <xs:sequence>
       <xs:element name="info">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" minOccurs="1"/>
              <xs:element name="autor" minOccurs="1"/>
              <xs:element name="email" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="version" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="fecha" minOccurs="0" maxOccurs="unbounded" type="xs:date"/>
            </xs:sequence>
          </xs:complexType>
       </xs:element>
       <xs:element name="par" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="q" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="qtext" minOccurs="1"/>
                  <xs:element name="a" minOccurs="1"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
       </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gitnew22/xml/win.xml
<?xml version="1.0" encoding="UTF-8"?>
<faq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="win.xsd">
  <info>
    <titulo>windows98</titulo>
    <autor>fernando</autor>
    <email>fer@yahoo.com</email>
    <version>1.0</version>
    <fecha>1999-05-01</fecha>
  </info>
  <par>
    <q>
      <qtext>porque?</qtext>    
      <a>porque si</a>
    </q>
    <q>
      <qtext>porque win95</qtext>
      <a>porque 95</a>
    </q>
  </par>
</faq>
